version: '3.8'

services:
  db:
    image: mysql:8
    container_name: login-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: login_page_db
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - '3001:3001'
    depends_on:
      - db

volumes:
  db_data:
